# The language in this case has no bearing - we are going to be making use of "conda" for a
# python distribution for the scientific python stack.
language:
  - python

env:
  global:
    # destination conda channel s
    - DESTINATION_CONDA_CHANNEL="rlizzo"
    - CONDA_INSTALL_LOCN="${HOME}/miniconda"
    # Secure variable defines the BINSTAR_TOKEN (anaconda cloud) API KEY for rlizzo repository. 
    - secure: C6nx2DoIzYFpPYoLPNV1eKYhBQGZ77ZePXRWJVFtMQPaG2ViM2tOtcwUvQmE7CihhZsqGtIKtBsIeH8qVk4NDDKd5waaj2Jv8UP1PXv8mRgPoMhFnR5i5SWQ86f3P/8VyXDokHSabIwPryvozgjGknQlWkYryLiDOrZj87A10zWG10eHo1tn6pQfcCHvNlqcRQzs8bxtEm0k81X/IrI5o7fK3GIk7MILowwK9tBFNGkOcs8RIzHNzLkwfnMbI5uI0+vPlX4aNUbBDC/r8IxIkTPjxPcfEjnJdMpPH8PnWR59PbEy6NaFbMnuG5w+saOVCbGh8GV2mQQkImoDw7aunmw5B9C31hRIHmMoEEQHgr+K3KOthx0XyLNHVamxWu5ISWjipfY4pSmCoGDMiMr2fzpghgpExKwD8SH7iuCPdOVhcdk5elV6vJ89hcxh4VA8owC0HSNQ092Z74TylzcZfkJPRHC+H/0lEcQmSxSLkc/ZbnBpvOSYaMf+iOk5nVzcRAQ9kYw1sM8yrcZ/rETgAPCvijxuDNVgkF2GHGjfD9HzxmGyNAsFjRKAj5BO2yfMJ1q0TT2uFSkOifF0c2zcGJ73fJBreecfjce3hvmC71HFf/BeLNEuxNGKx77lvC52AgheK+JYWMhhcQa2U/+mLHtjoN99PXMdJsAQcrxy2mU=


matrix:
  include:
    # Matrix expansion to run all subsequent builds with each OS.
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: MATRIX_EVAL="PACKAGE=itk && TRPYTHON_VERSION=3.6 && CC=gcc-7 && CXX=g++-7"
    - os: osx
      osx_image: xcode9.2
      compiler: clang
      env: MATRIX_EVAL="PACKAGE=itk && TRPYTHON_VERSION=3.6"

    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: MATRIX_EVAL="PACKAGE=vtk && TRPYTHON_VERSION=2.7 && CC=gcc-7 && CXX=g++-7"
    - os: osx
      osx_image: xcode9.2
      compiler: clang
      env: MATRIX_EVAL="PACKAGE=vtk && TRPYTHON_VERSION=2.7"
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: MATRIX_EVAL="PACKAGE=vtk && TRPYTHON_VERSION=3.5 && CC=gcc-7 && CXX=g++-7"
    - os: osx
      osx_image: xcode9.2
      compiler: clang
      env: MATRIX_EVAL="PACKAGE=vtk && TRPYTHON_VERSION=3.5"
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: MATRIX_EVAL="PACKAGE=vtk && TRPYTHON_VERSION=3.6 && CC=gcc-7 && CXX=g++-7"
    - os: osx
      osx_image: xcode9.2
      compiler: clang
      env: MATRIX_EVAL="PACKAGE=vtk && TRPYTHON_VERSION=3.6"

    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: MATRIX_EVAL="PACKAGE=vmtk && TRPYTHON_VERSION=2.7.14 && CC=gcc-7 && CXX=g++-7"
    - os: osx
      osx_image: xcode9.2
      compiler: clang
      env: MATRIX_EVAL="PACKAGE=vmtk && TRPYTHON_VERSION=2.7.14"
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: MATRIX_EVAL="PACKAGE=vmtk && TRPYTHON_VERSION=3.5.1 && CC=gcc-7 && CXX=g++-7"
    - os: osx
      osx_image: xcode9.2
      compiler: clang
      env: MATRIX_EVAL="PACKAGE=vmtk && TRPYTHON_VERSION=3.5.1"
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: MATRIX_EVAL="PACKAGE=vmtk && TRPYTHON_VERSION=3.6.1 && CC=gcc-7 && CXX=g++-7"
    - os: osx
      osx_image: xcode9.2
      compiler: clang
      env: MATRIX_EVAL="PACKAGE=vmtk && TRPYTHON_VERSION=3.6.1"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - source continuous-integration/travis/install.sh

script:
  - conda build --skip-existing --token $BINSTAR_TOKEN --user rlizzo --python $TRPYTHON_VERSION --no-copy-test-source-files $TRAVIS_BUILD_DIR/$PACKAGE/
