vtk:
  - 8.1.0

vtk_major_minor:
  - 8.1

vtk_md5:
  - "4fa5eadbc8723ba0b8d203f05376d932"

python:
  - 2.7
  - 3.5
  - 3.6 

c_compiler:
  - vs2015           # [win and (py36 or py35)]

cxx_compiler:
  - vs2015           # [win and (py36 or py35)]

CONDA_BUILD_SYSROOT:
  - $HOME/MacOSX-SDKs/MacOSX10.9.sdk   # [osx]
