itk:
  - 4.13.0
  
c_compiler:
  - vs2008           # [win and py27]
  - vs2015           # [win and (py36 or py35)]

cxx_compiler:
  - vs2008           # [win and py27]
  - vs2015           # [win and (py36 or py35)]

CONDA_BUILD_SYSROOT:
  - $HOME/MacOSX-SDKs/MacOSX10.9.sdk   # [osx]
